version: 2.1

orbs:
  kubernetes: circleci/kubernetes@0.12.0
  docker: circleci/docker@1.7.0

jobs:
  build_app:
    docker:
      - image: cimg/python:3.8.11
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: |
            make setup
            . .capstone/bin/activate
            make install
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

  getpods:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - kubernetes/install-kubeconfig:
          kubeconfig: KUBECONFIG_DATA
      - kubernetes/install-kubectl
      - run:
          name: Install aws-iam-authenticator
          command: |
            sudo make aws-iam
      - run:
          name: Get pods
          command: |
            kubectl get pods

workflows:
  get_ip:
    jobs:
      - build_app
#      - getpods