version: 2.1

orbs:
  kubernetes: circleci/kubernetes@0.12.0
  docker: circleci/docker@1.7.0

jobs:
  build_app:
    docker:
      - image: cimg/python:3.8.11
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: |
            make setup
            . .capstone/bin/activate
            make install
      - run:
          name: Lint source files
          command: |
            . .capstone/bin/activate
            make lint
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Build docker image
          command: |
            make build_docker
      - docker/check
      - run:
          name: Push docker image
          command: |
            make push_docker
      
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

  deploy_to_k8s:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - kubernetes/install-kubeconfig:
          kubeconfig: KUBECONFIG_DATA
      - kubernetes/install-kubectl
      - run:
          name: Install aws-iam-authenticator
          command: |
            sudo make aws-iam
      - run:
          name: Deploy green apps into EKS
          command: |
            bin/deploy_green_app.sh
            kubectl get pods

workflows:
  get_ip:
    jobs:
      - build_app
#      - deploy_to_k8s 